version: '3'

services:
  users_db:
    image: postgres:11-alpine
    env_file: ./.env
    volumes:
      - users_data:/var/lib/postgresql/data
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432

  users_service:
    build:
      context: .
      dockerfile: ./dev.dockerfile
    env_file: ./.env
    volumes:
      - .:/app
    ports:
      - 8000:8000

volumes:
  users_data: 