version: '3.5'

services:
  users_db:
    container_name: users_db
    image: postgres:11-alpine
    env_file: ./.env
    volumes:
      - users_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 54322:5432
    networks:
      - users

  users_service:
    container_name: users_service
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    environment:
      - DB_CON=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?sslmode=${POSTGRES_SSL}
      - DB_CON_TEST=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB_TEST}?sslmode=${POSTGRES_SSL}
    volumes:
      - .:/app
    command: reflex -c /app/reflex.conf
    ports:
      - 8000:8000
    networks:
      - teamreel
      - users

volumes:
  users_data: 

networks:
  teamreel:
    name: teamreel
  users:
    name: teamreel_users