version: '3'

services:
  users_db:
    container_name: users_db
    image: postgres:11-alpine
    env_file: ./.env
    volumes:
      - users_data:/var/lib/postgresql/data
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432

  users_service:
    container_name: users_service
    build:
      context: .
      dockerfile: ./dev.dockerfile
    env_file: ./.env
    environment:
      - DB_CON=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?sslmode=${POSTGRES_SSL}
      - DB_CON_TEST=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB_TEST}?sslmode=${POSTGRES_SSL}
    command: reflex -c reflex.conf
    volumes:
      - .:/app
    ports:
      - 8000:8000

volumes:
  users_data: 