version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: |
          curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
          chmod +x ~/docker-compose
          sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - run: |
          touch .env
          echo "POSTGRES_USER=usersadmin" >> .env
          echo "POSTGRES_PASSWORD=usersadmin" >> .env
          echo "POSTGRES_DB=users-service" >> .env
          echo "POSTGRES_DB_TEST=users-service-test" >> .env
          echo "POSTGRES_HOST=users_db" >> .env
          echo "POSTGRES_SSL=disable" >> .env
      - run: |
          docker-compose up -d
          docker exec -it -e APP_ENV=test -e POSTGRES_DB=$POSTGRES_DB_TEST users_service go test -v ./tests/...