name: Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/checkout@master
      - name: Populate .env file
        run: |
          touch .env
          echo "POSTGRES_USER=usersadmin" >> .env
          echo "POSTGRES_PASSWORD=usersadmin" >> .env
          echo "POSTGRES_DB=users-service" >> .env
          echo "POSTGRES_DB_TEST=users-service-test" >> .env
          echo "POSTGRES_HOST=users_db" >> .env
          echo "POSTGRES_SSL=disable" >> .env
      - name: Build the docker-compose stack
        run: docker-compose up -d
      - name: Test
        run: |
          source ./.env
          docker ps -a
          sleep 10
          docker ps -a
          sleep 30
          echo "USERS SERVICE LOGs"
          docker logs users_service
          echo "DB LOGS"
          docker logs users_db
          sleep 10
          docker exec users_service go test -v ./tests/...
          # docker ps -a
