name: Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@master
      - name: Build the docker-compose stack
        run: |
          touch .env
          echo "POSTGRES_USER=usersadmin" >> .env
          echo "POSTGRES_PASSWORD=usersadmin" >> .env
          echo "POSTGRES_DB=users-service" >> .env
          echo "POSTGRES_DB_TEST=users-service-test" >> .env
          echo "POSTGRES_HOST=users_db" >> .env
          echo "POSTGRES_SSL=disable" >> .env
          source .env
          # env
          docker-compose up -d --env-file=.env
      - name: Test
        run: |
          # echo "POSTGRES_USER=usersadmin" >> .env
          # echo "POSTGRES_PASSWORD=usersadmin" >> .env
          # echo "POSTGRES_DB=users-service" >> .env
          # echo "POSTGRES_DB_TEST=users-service-test" >> .env
          # echo "POSTGRES_HOST=users_db" >> .env
          # echo "POSTGRES_SSL=disable" >> .env
          source .env
          env
          docker exec users_db /bin/sh -c "dropdb --if-exists -U $POSTGRES_USER $POSTGRES_DB_TEST && createdb -U $POSTGRES_USER $POSTGRES_DB_TEST"
          docker exec -e APP_ENV=test -e POSTGRES_DB=$POSTGRES_DB_TEST users_service go test -v ./tests/...
          # docker ps -a
