on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/checkout@master
      - name: Populate .env file
        run: |
          touch .env
          echo "POSTGRES_USER=usersadmin" >> .env
          echo "POSTGRES_PASSWORD=usersadmin" >> .env
          echo "POSTGRES_DB=users-service" >> .env
          echo "POSTGRES_DB_TEST=users-service-test" >> .env
          echo "POSTGRES_HOST=users_db" >> .env
          echo "POSTGRES_SSL=disable" >> .env
      - name: Build the docker-compose stack
        run: docker-compose up -d
      - name: Test
        run: |
          docker exec users_db /bin/sh -c \
            "dropdb --if-exists -U "${POSTGRES_USER}" "${POSTGRES_DB_TEST}" && createdb -U "${POSTGRES_USER}" "${POSTGRES_DB_TEST}""
          docker exec -e APP_ENV=test -e POSTGRES_DB="${POSTGRES_DB_TEST}" users_service go test -v ./tests/...
