on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/checkout@master
      - name: Build
        run: GOOS=linux GOARCH=amd64 go build -o app .
      - name: Test
        run: go test -v ./tests/...
