name: Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@master
      - name: Populate .env file
        run: |
          touch .env
          echo "POSTGRES_USER=usersadmin" >> .env
          echo "POSTGRES_PASSWORD=usersadmin" >> .env
          echo "POSTGRES_DB=users-service" >> .env
          echo "POSTGRES_DB_TEST=users-service-test" >> .env
          echo "POSTGRES_HOST=users_db" >> .env
          echo "POSTGRES_SSL=disable" >> .env
      - name: Build the docker-compose stack
        run: |
          source ./.env
          docker-compose up -d
      - name: Test
        run: |
          source ./.env
          docker ps -a
          sleep 10
          docker ps -a
          sleep 30
          echo "USERS SERVICE LOGs"
          docker logs users_service
          echo "DB LOGS"
          docker logs users_db
          sleep 10
          docker exec users_db /bin/sh -c "dropdb --if-exists -U $POSTGRES_USER $POSTGRES_DB_TEST && createdb -U $POSTGRES_USER $POSTGRES_DB_TEST"
          docker exec -e APP_ENV=test -e POSTGRES_DB=$POSTGRES_DB_TEST users_service go test -v ./tests/...
          # docker ps -a
